In [1]:
import pandas as pd
import joblib

In [2]:
model_path = "../models/balanced_logistic_regression.pkl"

In [3]:
model = joblib.load(model_path)

In [4]:
sample_customer = pd.DataFrame([{
    "status": 1,
    "duration": 24,
    "credit_history": 2,
    "purpose": 3,
    "amount": 3000,
    "savings": 2,
    "employment_duration": 3,
    "installment_rate": 4,
    "personal_status_sex": 3,
    "other_debtors": 1,
    "present_residence": 2,
    "property": 2,
    "age": 35,
    "other_installment_plans": 3,
    "housing": 2,
    "number_credits": 1,
    "job": 3,
    "people_liable": 2,
    "telephone": 1,
    "foreign_worker": 2
}])

In [5]:
sample_customer

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,present_residence,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker
0,1,24,2,3,3000,2,3,4,3,1,2,2,35,3,2,1,3,2,1,2


In [6]:
prediction = model.predict(sample_customer)
prediction

array([0])

In [7]:
prediction_label = "Kötü kredi riski" if prediction[0] == 0 else "İyi kredi riski"

prediction_label

'Kötü kredi riski'

In [8]:
prediction_proba = model.predict_proba(sample_customer)
prediction_proba

array([[0.68343065, 0.31656935]])

Bunu şöyle okuyabiliriz:
0 sınıfı olasılığı = %68.3
1 sınıfı olasılığı = %31.7

Yani model bu müşteri için:
%68.3 kötü kredi riski
%31.7 iyi kredi riski
gibi bir değerlendirme yapmış.

In [9]:
bad_credit_probability = prediction_proba[0][0]
good_credit_probability = prediction_proba[0][1]

print("Kötü kredi olasılığı:", round(bad_credit_probability, 3))
print("İyi kredi olasılığı:", round(good_credit_probability, 3))

Kötü kredi olasılığı: 0.683
İyi kredi olasılığı: 0.317


Bu aşamada kaydettiğim final modeli kullanarak tek bir örnek müşteri için tahmin yaptım. Model bu müşteri için kötü kredi riski tahmini verdi. Tahmin olasılıklarına baktığımda kötü kredi olasılığı yaklaşık %68.3, iyi kredi olasılığı ise yaklaşık %31.7 çıktı.

Bu sonuç, kaydedilen modelin yeni bir müşteri verisi üzerinde kullanılabildiğini gösteriyor. Gerçek kullanımda kullanıcıdan alınan müşteri bilgileri bu formatta modele verilebilir ve model kredi riski tahmini üretebilir.